name: Mirror to GipHot

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          repository: Parsa307/uzbekmedia

      - name: Push to GipHot
        run: |
          git remote add giphot https://UzbekTeam:${{ secrets.GIPHOT_TOKEN }}@giphot.uzbek.digital/UzbekTeam/uzbekmedia.git
          git push --prune giphot 'refs/heads/*:refs/heads/*' 'refs/tags/*:refs/tags/*'
